int		isascii(char arg);
int		isalnum(char arg);
int		isalpha(char arg);
int		isdigit(char arg);
int		isprint(char arg);
int		tolower(int arg);
int		toupper(int arg);
int		strlen(char *arg);
char	*strchr(char *arg, int c);
char	*strrchr(char *arg, int c);
int		strncmp(char *arg1, char *arg2, unsigned int max);
char	*strnstr(const char *str, const char *to_find, unsigned int len);
char	*strcat(char *dest, char *src);
unsigned int	strlcat(char *dest, const char *src, unsigned int size);
int		atoi(const char *str);
char	*strdup(const char *s);
void	*memset(void *s, int c, unsigned int n);
void	*memcpy(void *dest, const void *src, unsigned int n);
void	*malloc(unsigned int size);

void	*calloc(unsigned int nmemb, unsigned int size);
void	bzero(void *s, unsigned int n);
void	*memmove(void *dest, const void *src, unsigned int n);
void	*memchr(const void *s, int c, unsigned int n);
int		memcmp(const void *s1, const void *s2, unsigned int n);